# Generated by Django 3.2.23 on 2024-12-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scale',
            constraint=models.UniqueConstraint(fields=('user', 'device', 'date'), name='scale_unique_user_device_date'),
        ),
        migrations.AddConstraint(
            model_name='scanwatchintraactivity',
            constraint=models.UniqueConstraint(fields=('user', 'device', 'date_heart_rate'), name='scanwatch_intra_unique_user_device_date_heart_rate'),
        ),
        migrations.AddConstraint(
            model_name='scanwatchsummary',
            constraint=models.UniqueConstraint(fields=('user', 'device', 'date'), name='scanwatch_summary_unique_user_device_date'),
        ),
        migrations.AddConstraint(
            model_name='sleepmatintraactivity',
            constraint=models.UniqueConstraint(fields=('user', 'device', 'start_date'), name='sleep_intra_unique_user_device_start_date'),
        ),
        migrations.AddConstraint(
            model_name='sleepmatsummary',
            constraint=models.UniqueConstraint(fields=('user', 'device', 'start_date'), name='sleep_summary_unique_user_device_start_date'),
        ),
    ]
