# Generated by Django 3.2.23 on 2024-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20240826_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepmatsummary',
            name='hr_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='hr_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='rr_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='rr_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='snoring_episodes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='snoring_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='hr_date_af',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='hr_date_rr',
            field=models.DateField(blank=True, null=True),
        ),
    ]
